### ISSUE TITLE
Sort unique

### ISSUE THREAD

**Issue by eddiemonge** [atom/sort-lines#10]
Sort unique doesn't seem to sort lines that have the same beginning things. For example, try sorting:

``` json
{
  "node": true,
  "esnext": true,
  "bitwise": true,
  "camelcase": true,
  "curly": true,
  "eqeqeq": true,
  "immed": true,
  "indent": 2,
  "latedef": true,
  "newcap": true,
  "noarg": true,
  "quotmark": "single",
  "regexp": true,
  "undef": true,
  "unused": true,
  "strict": true,
  "trailing": true,
  "smarttabs": true,
  "white": true
  "eqnull": true,
  "globalstrict": true,
  "strict": false
}
```

With sort:unique. Things like stricts don't line up. Sort unique should sort the items and then dedupe the list.

**Comment by eddiemonge** [comment]
It could but I think the name should be changed to something else like `Sort: De-dupe` or preferably, remove the functionality from here and into its own module.

**Comment by eddiemonge** [comment]
Adding support to my last comment, even the code doesn't think its a sort :wink: https://github.com/atom/sort-lines/blob/master/lib/sort-lines.coffee#L36

**Comment by jasonrudolph** [comment]
> It could but I think the name should be changed to something else like `Sort: De-dupe` or preferably, remove the functionality from here and into its own module.

/cc https://github.com/atom/sort-lines/pull/3#issuecomment-38822219 for related discussion
