### ISSUE TITLE
Feature request: Sort numeric

### ISSUE THREAD

**Issue by robballou** [atom/sort-lines#14]
Currently the sorting is by using string comparisons, so sorting numbers like:

    1
    20
    100

Will return:

    1
    100
    20

I guess this should be a separate command, although it looks like localeCompare has a [numeric option](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare). I'm not sure if that's worth turning on for the default commands or if it should be separate. Thanks!

**Comment by martinlindhe** [comment]
I think what you're requesting is a "natural sort" order, here's a good writeup on the differences: http://blog.codinghorror.com/sorting-for-humans-natural-sort-order/

**Comment by robballou** [comment]
Yeah, natural sort makes sense. I don't think the localCompare numeric option will work, but I haven't tested it.

**Comment by aioue** [comment]
Looks like this has been requested and addressed separately in #47.

**Comment by lee-dohm** [comment]
Yep, closing this as duplicate in favor of #47 since it has a PR associated with it. Please subscribe there for updates.
