### ISSUE TITLE
Shuffle is also needed. In this package?

### ISSUE THREAD

**Issue by xpol** [atom/sort-lines#24]
I'd like to add a `Shuffle` feature to his package or others.

As already merged #3 and pending #23, and if we add `shuffle` to this package, the package name `sort-lines` would not fit.

Or shall I create a new package based on this package and add `shuffle` there?

**Comment by kevinsawicki** [comment]
I think adding shuffle to this package makes sense, a PR would be great.

**Comment by tomByrer** [comment]
@xpol; how about PR your code?
https://github.com/xpol/atom-lines/blob/master/lib/lines.coffee#L41

**Comment by xpol** [comment]
@tomByrer 
Thank you for attention!
Why not have a try for [lines](https://atom.io/packages/lines) package? `apm install lines`.

**Comment by Bifros7** [comment]
I don't think adding shuffle to this package makes sense - it's the exact opposite of what I expect it to do. Also, what is the use-case for a shuffle option?

**Comment by tomByrer** [comment]
Use cases:
Using source that is alphabetical, but needing randomness for testing, abstraction, build your own lorium ipsum... often the flip-side of reasons why one needs alphabetical.

@xpol I'd prefer only 1 repo that is well maintained, rather than a bunch of forks.

**Comment by jasonrudolph** [comment]
Thanks to @vinkla's contribution in #79, the latest version of the `sort-lines` package (v0.16.0) adds support for the `sort-lines:shuffle` command.
