### ISSUE TITLE
case sensitive sort

### ISSUE THREAD

**Issue by jzinn** [atom/sort-lines#27]
All sorting is now case insensitive.

Both `Sort Lines: Sort` and `Sort Lines: Case Insensitive Sort` do the same thing, and there is no `Sort Lines: Case Sensitive Sort`.

Can there be a way to do a case sensitive sort?

**Comment by izuzak** [comment]
> All sorting is now case insensitive.

Strange, I'm not seeing that behavior. Here's what I tried:

1) Input:

```
A
b
B
a
```

2) `Sort Lines: Sort` results in this:

```
A
B
a
b
```

3) `Sort Lines: Case Insensitive Sort` results in this:

```
A
a
b
B
```

@jzinn Are you seeing different behavior?

**Comment by jzinn** [comment]
I recorded a video:
![insensitive](https://cloud.githubusercontent.com/assets/79761/8444210/27e12c86-1f43-11e5-8bea-8c908c139b5e.gif)

For 2), the video shows the result as
```
a
A
b
B
```

3) is interesting inconsistent, in that `A` comes before `a`, but `b` comes before `B`.

This is with Atom 1.0.0 and sort-lines 0.11.0.

**Comment by jzinn** [comment]
It's working correctly in Atom 1.0.2.

**Comment by jzinn** [comment]
Sorting is case insensitive again in Atom 1.0.7.
