### ISSUE TITLE
Preserve the new lines between lines

### ISSUE THREAD

**Issue by li-xinyang** [atom/sort-lines#30]
![image](https://cloud.githubusercontent.com/assets/3349406/8645052/80fcdd64-2976-11e5-8dfa-87f95fd2fbd1.jpg)

**Comment by eddiemonge** [comment]
What happens in there are two new lines between an item? How do you know which spacing to preserve? I think this is more of a workflow then a feature for this module.

**Comment by kachkaev** [comment]
I agree with @li-xinyang – this would be useful. I also have some markdown lists with blank lines that I sort manually from time to time (e.g. a list of Atom packages that I'm using with a short description). Having sorting done automatically would help a lot! I would not worry about special cases like the @eddiemonge mentioned. If the list is not matching `line - blank [- line - blank] - line` pattern, the script can fallback to its default behaviour (like it is shown on a screenshot).

`ctrl+alt+g` behaves similarly when copying and pasting: if the number of blocks in the buffer equals to the current number of cursors, a single block gets pasted per cursor. If the numbers mismatch, all the buffer is pasted at each cursor. It is easy to spot the differences between the two behaviours and figure out why the result is not what has been excepted.

**Comment by ostrokach** [comment]
Package version: 0.18.0
Atom version: 1.21.1
OS: Linux Mint 18.2
Steps: Select test → `Ctr-Shift-P` → `Sort lines: Sort`

**Comment by jasonrudolph** [comment]
Thanks for the submission!

It sounds like this would be useful in some people's workflows. However, it is not something that is within the scope that we have have envisioned for this package. For that reason, I'm going to close this.

If you're interested in building a package that provides this behavior, the Atom Flight Manual has a [section on publishing your own packages](https://flight-manual.atom.io), and you can always feel free to ask any questions you have on [Discuss (the official Atom and Electron message board)](https://discuss.atom.io) or the Atom Slack team.
