### ISSUE TITLE
Sort sometimes acts like case insensitive sort

### ISSUE THREAD

**Issue by hankhsiao** [atom/sort-lines#33]
Every time I reopen Atom, the sorting sequence changes when sorting. Here is my result when performing sort.

```
A
B
c
D
e
```

Sometimes, it is correct

```
A
B
D
c
e
```

**Comment by jdelisle** [comment]
It's broken too on my editor as well. In my case Sort always runs as case insensitive, making it useless for me as it is right now. Running on OSX.

Sorting this doesn't do anything :
```
'test1',
'Test2',
'test3',
'Test4',
```

**Comment by ianobermiller** [comment]
Just noticed this as well, the default seems to be case insensitive.

**Comment by tschaub** [comment]
It looks like the `lines` package correctly sorts: https://atom.io/packages/lines

**Comment by ianobermiller** [comment]
@tschaub yep, that is what I've been using instead.

**Comment by ulidtko** [comment]
> It looks like the lines package correctly sorts: https://atom.io/packages/lines

:+1:

**Comment by lee-dohm** [comment]
The sort-lines package has separate commands now for various sort types.

**Comment by ulidtko** [comment]
> The sort-lines package has separate commands now for various sort types.

Except that they don't work. 

Open new buffer, input:

    test-dfoo
    test-bfoo
    test
    test-afoo
    test-Cfoo

**Comment by ulidtko** [comment]
Also, I had another trouble when sorting a long run of XML lines like this:
```
<tag>test-dfoo</tag>
<tag>test-bfoo</tag>
<tag>test</tag>
<tag>test-afoo</tag>
<tag>test-Cfoo</tag>
```

After F5, guess what, the `<tag>test</tag>` ends up *in the end of the list*:
```
<tag>test-afoo</tag>
<tag>test-bfoo</tag>
<tag>test-Cfoo</tag>
<tag>test-dfoo</tag>
<tag>test</tag>
```

I'm not going to be particularly constructive in my ignorance of ASCII ordering for non-alphanumeric symbols, but I'd really want to see `<tag>test</tag>` being sorted *to the top* of the list — since it's the shortest value there.

Perhaps, maybe stripping common suffix+prefix would help?.. I don't know. As a user, I've already exhausted any reasonable energy+thought budget worth such a simple plugin.

**Comment by lee-dohm** [comment]
Whoops, you're right. My mistake :grinning:

**Comment by ulidtko** [comment]
Props for admitting that :)
Hope to see a fix soon!

**Comment by ulidtko** [comment]
Still repro's on Atom 1.12.7 & sort-lines@0.18.0.

`sort-lines:sort` and `sort-lines:case-insensitive-sort` have the same effect on the test from [this comment](33#issuecomment-192378312), where they shouldn't.

**Comment by lee-dohm** [comment]
@ulidtko We don't support Atom v1.12.7 anymore ... v1.21.1 is the latest Stable version: https://github.com/atom/atom/releases/latest

**Comment by ulidtko** [comment]
@lee-dohm I've just retested with Atom 1.21.2, sort-lines 1.18.0 (latest). Same behavior.

Your test (#90) is passing, but [mine]((33#issuecomment-192378312) doesn't. Would you want to add a better test (and reopen the issue) ?

**Comment by Ben3eeE** [comment]
@ulidtko Your test is not documenting what sort order you are getting after sorting and what order you expect. Can you please add this information :bowing_man:

**Comment by ulidtko** [comment]
@Ben3eeE yes, sure. Comment updated.

**Comment by lee-dohm** [comment]
@ulidtko We're using the case-sensitive sorting using JavaScript's [`String.localeCompare` function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare). If you have an issue with how it is sorting things, you should file a bug with the Chromium project.

**Comment by ulidtko** [comment]
@lee-dohm well. I see

    var lines = ['test-dfoo', 'test-bfoo', 'test', 'test-afoo', 'test-Cfoo']
    lines.sort((a, b) => a.localeCompare(b, 'en-US'))
    (5) ["test", "test-afoo", "test-bfoo", "test-Cfoo", "test-dfoo"]

but somehow, the default array sort works great (at least with ascii):

    var lines = ['test-dfoo', 'test-bfoo', 'test', 'test-afoo', 'test-Cfoo']; lines.sort()
    (5) ["test", "test-Cfoo", "test-afoo", "test-bfoo", "test-dfoo"]

I also seem unable to find any way to make `String.localeCompare` respect case ordering before letter ordering. "Implementations are not required to support `caseFirst` property", as the doc says.

Which begs the question...
Why use an API which seems incapable of doing what it's supposed to do?
Any known issues with the default string sort?

**Comment by ulidtko** [comment]
I mean, let `localeCompare` do the case-insensitive sorting as it's done now.

Only change the default sort to... the default sort. Looks like [the line here](/atom/sort-lines/blob/master/lib/sort-lines.js#L44) is the root cause of the issue.

**Comment by lee-dohm** [comment]
Thanks for the suggestion. We're leaving it the way it is.

**Comment by ulidtko** [comment]
> Thanks for the suggestion. We're leaving it the way it is.

Meaning: "We're leaving it broken (but Unicode-aware!)" -- rather than make it work for ASCII only.

Nice. It's a good thing packages are forkable.

**Comment by FelixVicis** [comment]
@lee-dohm I suggest you put in the documentation that the sort is broken then.
