### ISSUE TITLE
Sort by line length

### ISSUE THREAD

**Issue by smutnyleszek** [atom/sort-lines#37]
I could use such a feature occasionally. Don't know if it would be hard to implement and really useful for more people though.

**Comment by jpaulin** [comment]
So, primarily first by line length, then the internal sorting within equal line lengths would be done by another criteria?

**Comment by smutnyleszek** [comment]
Yes. Probably alphabetically as default.

So this text:

```
One
Two
Three
Four
Five
Six
Seven
Eight
Nine
Ten
Eleven
Twelve
```

Will end up being:

```
One
Six
Ten
Two
Five
Four
Nine
Eight
Seven
Three
Eleven
Twelve
```

**Comment by eddiemonge** [comment]
What is the purpose of this other than visually pretty code?

**Comment by smutnyleszek** [comment]
I don't need this for code per se. This would be occasionally helpful for me when I need to quickly work on some data, i.e. to fix some JSON translations by length. And I would use it rarely when writing some poetry/essays in Atom.

**Comment by eddiemonge** [comment]
> fix some JSON translations by length

Not really sure what that means.

You would sort poetry/essays? Wouldn't that change the meaning?

Perhaps you could fork this and add it in a new command, like lengthSort, instead of doing it here?

**Comment by iest** [comment]
I opened a PR for this as it was something I missed from a package I used on ST3: https://github.com/atom/sort-lines/pull/48

**Comment by jm3** [comment]
This would also be handy for me. I use Atom as a general text editor in addition to coding, and I need this from time to time. Would be nice if the sort package had this option instead of requiring my to shell out to awk and remember the incantation `cat testfile | awk '{ print length, $0 }' | sort -n -s | cut -d" " -f2-`. I understand it's not a common request, tho. Would you accept a PR for it?

**Comment by jasonrudolph** [comment]
> Would you accept a PR for it?

@jm3: Yes. :bow:

**Comment by mfour-merickson** [comment]
Any chance this has been added?  I use this feature ALL THE TIME in PHPStorm and would love to have it in Atom.  I use it to keep all my "use" commands sorted by length.

**Comment by jasonrudolph** [comment]
Thanks to @mateuspv's contribution in #80, the latest version of the sort-lines package (v0.17.0) includes a `sort-lines:by-length` command.

**Comment by mikeerickson** [comment]
Awesome!!!
