### ISSUE TITLE
Improper sorting

### ISSUE THREAD

**Issue by kirkstrobeck** [atom/sort-lines#40]
When sorted, this

```
"body"
"body-txt"
```

becomes this

```
"body-txt"
"body"
```

**Comment by Tyriar** [comment]
I don't think this is a bug since the `"` char comes before `-`. If you remove the double quotes it should work fine.

**Comment by kirkstrobeck** [comment]
:+1:

**Comment by kirkstrobeck** [comment]
It looks like an error plainly, but you’re objectively correct
