### ISSUE TITLE
Sorting international characters

### ISSUE THREAD

**Issue by mrodalgaard** [atom/sort-lines#41]
There are still some problems with sorting international characters, like the danish characters 'æ', 'ø', 'å' using `localeCompare`. I believe the sort goes wrong because navigator.language is set to 'English' (in my Atom version at least).

I propose a config that sets an optional locale parameter on all `localeCompare` calls, like implemented [HERE](https://github.com/mrodalgaard/sort-lines/blob/sort-international-characters/lib/sort-lines.coffee). Else there has to be a way to change the language locale globally in Atom/Electron in a more general way then mentioned [by pracucci](https://github.com/atom/electron/issues/2484).

**Comment by rasenplanscher** [comment]
I think, having a way to set the project's locale irrespective of the editor's settings would be great. If I were to work on a Danish project, I'd like to sort by Danish locale, on Spanish projects that wouldn't do.
