### ISSUE TITLE
Feature request: Sort in a line for comma separated text.

### ISSUE THREAD

**Issue by camjc** [atom/sort-lines#43]
It would be cool if I could sort a list of arguments like

`foo, bar, baz`

that are all on one line.
I guess the sorter would notice that the current selection was only one line and look for commas, then apply its normal sorting order.
One use case would be if you're doing ES2015 or CoffeeScript destructuring and want sorted keys in a destructuring object.

**Comment by thedaniel** [comment]
Thanks for the feature request, sounds useful.

**Comment by mherodev** [comment]
There still isn't a package for this? This is some low-hanging fruit!

**Comment by rasenplanscher** [comment]
What about [sort-words](https://atom.io/packages/sort-words)?

**Comment by rasenplanscher** [comment]
Also, this is addressed largely by #68 – should be linked, I think

**Comment by jasonrudolph** [comment]
Thanks for the idea!

I could definitely see this being useful in some people's workflows. However, it is not something that is within the scope that we have have envisioned for this package: this package is focused on sorting lines relative to each other, but is not intended to alter the content of any individual line. For that reason, I'm going to close this issue.

This feature sounds like a cool idea for an Atom package though. (Perhaps it could be an addition to the [sort-words](https://atom.io/packages/sort-words) package that @rasenplanscher mentioned above.) If you need help building this as a package, please check out the [Atom Flight Manual section on publishing your own packages](https://flight-manual.atom.io) and feel free to ask any questions you have on [Discuss, the official Atom and Electron message board](https://discuss.atom.io) or the Atom Slack team.

Thanks again for contributing to Atom :star:
