### ISSUE TITLE
Sorting a line-range sometimes inserts extra lines

### ISSUE THREAD

**Issue by niklasfrykholm** [atom/sort-lines#44]
If you select these lines and sort them, an extra line is inserted at the end of the lines:

```
A
C
B
```

If the lines are already sorted, no extra line is inserted.

Tested with version 0.12.0

**Comment by tregusti** [comment]
:+1:

**Comment by lee-dohm** [comment]
I just tested this and cannot reproduce on the latest version, v0.18.0. Apparently, it has been fixed somewhere in the intervening time.
