### ISSUE TITLE
dash is sorted before colon 

### ISSUE THREAD

**Issue by ismay** [atom/sort-lines#46]
I encountered this issue when linting with stylelint (see [issue 480](https://github.com/stylelint/stylelint/issues/480)). Let's say I'm sorting these lines:

```css
  margin-top: 5px;
  margin: 0; /* this will hammer the line above */
```

Stylelint wants `margin` to be above `margin-top`, to prevent the shorthand overriding `margin-top` (and similar for other rules). But sort-lines sorts a `-` before a `:` and thus puts `margin` last. I don't know what would be the best way to solve this, but I was just wondering if the ordering of dash and colon is set in stone, or that it could be altered, since it does make sense to sort them differently for css.

**Comment by Tyriar** [comment]
The sort you're using is doing that because that's the order of the character codes. It sounds like you're after a smarter, language-aware sort which may be out of the scope of this package.

**Comment by ismay** [comment]
> The sort you're using is doing that because that's the order of the character codes.

Yeah, that's what I suspected, I can see how changing that would be weird. Thanks for the feedback!
