### ISSUE TITLE
Does not sort in .md file

### ISSUE THREAD

**Issue by asbjornu** [atom/sort-lines#53]
This plugin is not working for me in [this particular Markdown file](/PayEx/Development.Guidelines/blob/master/open-source-development-guidelines.md). The stuff I'm trying to sort is the link reference list at the very bottom of the file (edit it or view it raw to see it; it will of course be lost when rendered as HTML).

Copying and pasting the reference list to another tab and then sorting it works; it is sorted as expected.  Is there some sort of debug log from this plugin I can have a look at to see why it isn't sorting in this particular file?

**Comment by lee-dohm** [comment]
I can't reproduce the issue you're describing using Atom v1.4.1 on Mac OS X 10.11.3 and sort-lines v0.14.0. Have you followed the suggestions in the [Debugging document](https://atom.io/docs/latest/hacking-atom-debugging)? Also, could you give the following information?

* Which version of Atom are you using?
* What OS and version are you running?
* What version of sort-lines do you have installed?
* What line ending character(s) are you using?

**Comment by asbjornu** [comment]
This is weird. I tried sorting at home, on what I thought was the exact same installation of everything, but here it worked. Just for reference, this is what I have at home:

- Atom 1.4.1
- OS X 10.10.5
- sort-lines 0.14.0
- Does Atom have its own EOL config? If so, where do I find it?

I'll try the debug stuff at work (where I have the problem) on Monday to see if anything mentioned there may fix the problem. At home, `$ apm list --installed --bare` returns:

```
advanced-new-file@0.5.0
advanced-open-file@0.14.1
atom-beautify@0.28.21
atom-jade@0.3.0
atom-material-syntax@0.3.2
atom-material-ui@0.8.1
atom-yeoman@0.3.15
autocomplete-clang@0.8.9
clang-format@1.25.0
editorconfig@1.2.4
file-types@0.5.1
json-schema@0.1.15
linter@1.11.3
omnisharp-atom@0.26.9
php-composer-completion@0.3.4
predawn-syntax@1.0.2
predawn-ui@1.0.2
sort-lines@0.14.0
sublime-default-syntax@0.2.7
sync-settings@0.6.0
tabs-to-spaces@1.0.1
wordpress-api@1.2.1
```

It'll be interesting to see what the difference at work might be and who or what's to blame.

**Comment by asbjornu** [comment]
Oh man. Now it works on my work Mac as well. No way to debug why it didn't now, then. Well, well!

**Comment by lee-dohm** [comment]
Sorry that this has been so confusing, but I'm glad that things are working for you now! I missed your one question about EOL configuration and yes, Atom has the [line-ending-selector package](https://atom.io/packages/line-ending-selector) that allows you to configure which line endings to use interactively. It defaults to the platform default ... `LF` on Linux and OS X and `CRLF` on Windows.
