### ISSUE TITLE
sort by "keys"

### ISSUE THREAD

**Issue by stryju** [atom/sort-lines#57]
I think it would be useful to add a functionality to "sort by keys" (useful for json, css definitions)

source:

```
foo: 123
bar: 456
foo-bar: 789
bar-bar: 123
```

current result:

```
bar-bar: 123
bar: 456
foo-bar: 789
foo: 123
```

"sort by keys" result:

```
bar: 456
bar-bar: 123
foo: 123
foo-bar: 789
```

**Comment by tomByrer** [comment]
Good idea, but isn't this more of a 'sort with non alphanumeric characters last' request?

**Comment by lee-dohm** [comment]
Thanks for the feedback. This isn't a feature we're interested in adding to the sort-lines package. It sounds like a very interesting feature for another Atom package though!
