### ISSUE TITLE
Feature request...

### ISSUE THREAD

**Issue by onechrisjones** [atom/sort-lines#58]
Thanks for this awesome package. I appreciate your hard work. I hope this is the place to make some feature requests...

- a ‘prefix/suffix’ line function
- a ‘process duplicate lines’ function
- a ‘process lines containing’ function…

I think those functions could add some significant value to your package!

Thanks again.

**Comment by lee-dohm** [comment]
I'm not sure what these have to do with sorting lines? Can you be more specific in what you're looking for? On the face of it, they sound more like they have to do with the [find-and-replace package](https://github.com/atom/find-and-replace).

**Comment by onechrisjones** [comment]
Honestly, Xpol Wan, who forked your pkg and made the 'lines' pkg, recommended that i request these features here, as he can't implement them currently. Sorry to disturb you. Thanks for your time.

**Comment by lee-dohm** [comment]
Thanks for the ideas. It's no bother. If you have some more details around what you're looking for, you might want to try posting them on [Discuss, the official Atom message board](https://discuss.atom.io). Some package authors frequent there and perhaps one of them will pick up your ideas and run with them!

Good luck and thanks again for the feedback!
