### ISSUE TITLE
Keyboard shortcut

### ISSUE THREAD

**Issue by pzi** [atom/sort-lines#6]
Would be great to have/assign a keyboard shortcut (ie. Sublime: F5) instead of `cmd+shift+p+sor+return`

Thank you :)

**Comment by davecarter** [comment]
In addition to the keymapping I would like to point out that `sort-lines` package must be previously installed:

```
apm install sort-lines
```

Then you can use:

```
'.editor':
  'f5': 'sort-lines:sort'
````
as @pzi commented 

Thank you all for the info!
