### ISSUE TITLE
asciibetical sorting

### ISSUE THREAD

**Issue by thomir** [atom/sort-lines#61]
It would be great to be able to sort lines by ascii-betical ordering:

https://en.wiktionary.org/wiki/ASCIIbetical

I find myself working in a codebase where imports need to be ordered in this way, and being able to use the sort-lines package would be great.

**Comment by lee-dohm** [comment]
How is this different from the sort order already offered?

**Comment by thomir** [comment]
Consider the following lines:

```
alphabet
banana
Cupcake
diagram
Egg
Fixture
```

Atom currently sorts them into the above order: ignoring case. Asciibetical order would be the following:

```
Cupcake
Egg
Fixture
alphabet
banana
diagram
```

i.e.- uppercase and lowercase lines separated.

**Comment by gingerbeardman** [comment]
@thomir ASCIIbetical *is* upper and lower sorted distinctly.

What you're asking for is "case insensitive" or "natural" sorting. This is already supported: https://github.com/atom/sort-lines

**Comment by thomir** [comment]
@gingerbeardman Exactly. Please re-read my last comment. 

In any case, this can probably be closed now, since I no longer use atom, and it seems there's no interest from anyone else in this feature request (perhaps it even was already implemented since I opened the issue?).

**Comment by gingerbeardman** [comment]
Sorry @thomir a bit must have flipped in my brain.

To get what you wanted, choose: Atom > Edit > Lines > Natural

it's been in there since before your request, Jan 2016 https://github.com/atom/sort-lines/pull/50
