### ISSUE TITLE
Add the ability to sort by the selected text

### ISSUE THREAD

**Issue by dkniffin** [atom/sort-lines#64]
This plugin is awesome, but it's really only useful if the text you want to sort by is at the beginning of the line. I think it'd be immensely useful to add the ability to sort the user's current selection.

For example, if I have the following json blob:

```
[
  { id: 1, name: 'Bob' },
  { id: 2, name: 'Alice' },
  { id: 3, name: 'David' },
  { id: 4, name: 'Chester' },
]
```

Currently, I could sort by id, which is great, but what if I wanted to sort by the name? If "sort by selection" is added, I could use whatever method I want to make a multi-select of the names (eg: select the first `name`, cmd+d to get the rest, then arrow over to the value and select it), sort by selection, and voila, I've got it sorted by name.

Edit:
I started looking into making a PR for this, but got stuck. I didn't realize there's already some support for multi-cursors in a different way. Right now, it will sort all the selections independently. However, I think there's probably still a way to do this, but I'm not sure about the details right now.

**Comment by lee-dohm** [comment]
Thanks very much for the feedback! This isn't a feature that we're interested in adding to this package. It sounds like an awesome idea for a new Atom package though!
