### ISSUE TITLE
Feature: Sorting IP addresses

### ISSUE THREAD

**Issue by spanktar** [atom/sort-lines#73]
It would be great to be able to sort IP addresses!

For example, right now the following:

```
"52.199.127.192/26",
"13.32.0.0/15",
"34.195.252.0/24",
"204.246.164.0/22",
"52.84.0.0/15",
```

would sort to:

```
"13.32.0.0/15",
"204.246.164.0/22",
"34.195.252.0/24",
"52.199.127.192/26",
"52.84.0.0/15",
```

instead of the expected:

```
"13.32.0.0/15",
"34.195.252.0/24",
"52.84.0.0/15",
"52.199.127.192/26",
"204.246.164.0/22",
```

Note the added challenge of sorting by IP when the IPs might be bounded by something else, in this case quoted with trailing commas.

**Comment by jasonrudolph** [comment]
https://github.com/atom/sort-lines/pull/69 replaced the previous natural sort implementation with an implementation provided by the [javascript-natural-sort](https://www.npmjs.com/package/javascript-natural-sort). As a side effect of that change, the `sort-lines:natural` command now sorts IP addresses as described above.
