### ISSUE TITLE
Unable to sort code alphabetically

### ISSUE THREAD

**Issue by mightyspaj** [atom/sort-lines#76]
I'm unable to sort code alphabetically.

For instance, I've tried using both `sort-lines:sort` and `sort-lines:natural` to sort the following JS object in alphabetical order, but it does nothing:

```javascript
var styles = {
  color: COLOURS.WHITE,
  boxShadow: '0px 0px 10px 0px rgba(0,0,0,0.6)',
  backgroundColor: COLOURS.PRIMARY_DARK,
  maxWidth: '311px',
  padding: 0,
  userSelect: 'none',
}
```

In case this is a bug or something wrong with my configuration, here's some extra details:

**Restarted Atom after installing:** `true`
**OS:**  Ubuntu 17.04

`keymap.cson`
```cson
'sort-lines':
  'alt-f5': 'sort-lines:natural'
```

**Comment by jasonrudolph** [comment]
@mightyspaj: Thanks for reporting this issue. Can you please describe the specific steps required to reproduce this issue?

---

Note: The majority of @atom repositories include an [issue template](https://github.com/atom/tree-view/blob/a0e553ffc0073a03e1f944456c92cd48433efdfe/ISSUE_TEMPLATE.md#steps-to-reproduce) that automatically prompts you for this information when you open an issue:

```
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]
```

I'll look into getting an issue template added to this repository as well.

**Comment by mightyspaj** [comment]
Sure, sorry for missing that and the delay. Here's the reproduction steps:

### Steps to Reproduce

1. Add the following to Atom's `keymap.cson` file to configure the shortcut for sorting lines:
```cson
'sort-lines':
  'alt-f5': 'sort-lines:natural'
```

2. Select a group of lines inside a JavaScript object that aren't sorted alphabetically. Make sure to exclude the lines with the opening/closing brackets for the object. For example:

```javascript
var styles = {
  color: COLOURS.WHITE,
  boxShadow: '0px 0px 10px 0px rgba(0,0,0,0.6)', // Select this line
  backgroundColor: COLOURS.PRIMARY_DARK, // Select this line
  maxWidth: '311px',
  padding: 0,
  userSelect: 'none',
}
```

3. Press `alt + f5` (the shortcut configured in step 1) to sort the lines.

**Expected behavior:** the selected lines should be sorted alphabetically.

**Actual behavior:** nothing—no alphabetical sorting occurs.

**Comment by jasonrudolph** [comment]
@mightyspaj: Thanks for sharing that info. I think the problem has to do with the `keymap.cson` entry. The first line is a CSS selector that determines where in Atom the keyboard shortcut will be available. You probably want something like this, which makes the keyboard shortcut available in the text editor:

```
'atom-text-editor:not([mini])':
  'alt-f5': 'sort-lines:natural'
```

I think that will resolve the problem you're experiencing, so I'm going to close this issue. If you still run into problems after making that change to your `keymap.cson`, please let us know.
