### ISSUE TITLE
Package is not deactivated properly

### ISSUE THREAD

**Issue by 50Wliu** [atom/sort-lines#92]
### Description

After deactivating `sort-lines`, the commands are not disposed and still work, which is unexpected behavior. @jasonrudolph I can handle this if you want.  Have been doing a sweep of packages and making sure each one deactivates correctly recently.  The majority don't 😞.

### Steps to Reproduce

1. Activate package by using a command
2. Disable package
3. Open Command Palette and search for one of `sort-lines`' commands

**Expected behavior:** No results

**Actual behavior:** Command shows up and executes correctly

**Reproduces how often:** 100%

**Comment by jasonrudolph** [comment]
> @jasonrudolph I can handle this if you want.

@50Wliu: That wound be awesome. :zap:
