### ISSUE TITLE
requested feature: uniq -c

### ISSUE THREAD

**Issue by zhugw** [atom/sort-lines#95]
Sometimes actually I just want to stat, e.g. know which line is occurred most frequently? So could you support uniq count, just like below shell command

```
sort foo | uniq -c | sort -nr
```

**Comment by jasonrudolph** [comment]
:wave: Hi @zhugw: Thanks for the suggestion. It sounds like this would be useful in some people's workflows. However, it is not something that is within the scope that we have have envisioned for this package. (This package is focused focused on sorting lines. 😇 ) For that reason, I'm going to close this.

However, you might try the [shell-it](https://atom.io/packages/shell-it) package. I think it will allow you to accomplish the behavior you're looking for.

**Comment by zhugw** [comment]
@jasonrudolph shell-it is exactly what I want, Thanks!!!
