### ISSUE TITLE
key-value pairs (like JSON or JS objects) – shorter names are ordered after extended variations

### ISSUE THREAD

**Issue by matthiasdailey-ccri** [atom/sort-lines#97]
### Description

I noticed that the sorting algorithm sorts certain lines in a way that seems wrong, when the lines are key-value pairs like JSON or JS objects. 

### Steps to Reproduce

When sorting the following lines:
```
"abc": "value",
"abc-a": "value",
"abc-a-b": "value",
```
**Expected behavior:**
```
"abc": "value",
"abc-a": "value",
"abc-a-b": "value",
```

**Actual behavior:**
```
"abc-a-b": "value",
"abc-a": "value",
"abc": "value",
```

The resulting sort places the short names _after_ the extended names. Other tools do it the other way, which, to me, seems to be the natural expected order.

This also happens without quoted keys.

Any thoughts? Sorry for making your lives more complicated ;)

**Reproduces how often:** always

### Versions

⚡ atom --version
Atom    : 1.25.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

⚡ apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.25.0
python 2.7.12
git 2.7.4

**Comment by ptz0n** [comment]
Can reproduce.

**Comment by matthiasdailey-ccri** [comment]
@ptz0n thanks! That PR seems to address CSS only, and it appears to require you to use a non-default sorting command "sort-lines:css". But hey, if it works for JSON / JS objects too then I'm happy with that workaround.

**Comment by lee-dohm** [comment]
The sort-lines package is only intended to sort lines as a whole, not make semantic determinations about the contents of the lines.

See also #57
